### ISSUE TITLE
Kotlin Rewrite

### ISSUE THREAD

**Issue by ryanjokuti** [ryanjokuti/BluetoothStatsApp#5]
**Reasoning behind the feature request**
Due to concerns over the future of languages for Android apps, I'd prefer to switch to Kotlin early on to avoid rewriting a lot of code.

**Describe the solution you'd like**
The same app but in Kotlin.

**Concerns**
I don't know if Java-based libraries will stop working if we do go through with this.

**Additional context**
Working on this in a separate branch is preferable.

**Comment by garrettsummerfi3ld** [comment]
Seconded

**Comment by ryanjokuti** [comment]
Milestone made
